/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aha

type Release struct {
	// A unique identifier for the release.
	Id string `json:"id,omitempty"`
	// Release referenence number.
	ReferenceNum string `json:"reference_num,omitempty"`
	// Release name.
	Name string `json:"name,omitempty"`
	// Start date in YYYY-MM-DD format.
	StartDate string `json:"start_date,omitempty"`
	// Release date in YYYY-MM-DD format.
	ReleaseDate string `json:"release_date,omitempty"`
	// External release date in YYYY-MM-DD format.
	ExternalReleaseDate string `json:"external_release_date,omitempty"`
	Released            bool   `json:"released,omitempty"`
	ParkingLot          bool   `json:"parking_lot,omitempty"`
	// Web URL for release.
	Url string `json:"url,omitempty"`
	// API URL for release.
	Resource string `json:"resource,omitempty"`
}
