/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aha

import (
	"time"
)

// Feature struct for Feature
type Feature struct {
	Id            string        `json:"id,omitempty"`
	CreatedAt     time.Time     `json:"created_at,omitempty"`
	CommentsCount int64         `json:"comments_count,omitempty"`
	CustomFields  []CustomField `json:"custom_fields,omitempty"`
	// Due date in YYYY-MM-DD format.
	DueDate        string  `json:"due_date,omitempty"`
	Name           string  `json:"name,omitempty"`
	ProductId      string  `json:"product_id,omitempty"`
	ProgressSource string  `json:"progress_source,omitempty"`
	ReferenceNum   string  `json:"reference_num,omitempty"`
	Release        Release `json:"release,omitempty"`
	// API URL for the resource.
	Resource string `json:"resource,omitempty"`
	// Start date in YYYY-MM-DD format.
	StartDate string   `json:"start_date,omitempty"`
	Tags      []string `json:"tags,omitempty"`
	// Web UI URL for the resource.
	Url            string                `json:"url,omitempty"`
	WorkUnits      int64                 `json:"work_units,omitempty"`
	WorkflowStatus FeatureWorkflowStatus `json:"workflow_status,omitempty"`
}
