language: go
go_import_path: github.com/grokify/go-aha
go:
  - "1.15.x"
  - "1.14.x"
  - "1.13.x"
  - "1.12.x"
  - master
matrix:
  allow_failures:
    - go: "1.12.x"
    - go: master
sudo: true
install:
  - go get -t -v ./...
script:
  - go test -v ./...
