/* 
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package aha

import (
	"time"
)

type Initiative struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Url string `json:"url,omitempty"`

	Resource string `json:"resource,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`
}
