/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package aha

type InlineResponse200Pagination struct {
	TotalRecords int64 `json:"total_records,omitempty"`

	TotalPages int64 `json:"total_pages,omitempty"`

	CurrentPage int64 `json:"current_page,omitempty"`
}
