/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package aha

import (
	"regexp"
	"time"

	"github.com/grokify/gotilla/time/timeutil"
)

type InlineResponse200Features struct {
	Id string `json:"id,omitempty"`

	ReferenceNum string `json:"reference_num,omitempty"`

	Name string `json:"name,omitempty"`

	CreatedAt time.Time `json:"created_at,omitempty"`

	Url string `json:"url,omitempty"`

	Resource string `json:"resource,omitempty"`

	Initiative InlineResponse200Initiative `json:"initiative,omitempty"`

	DueDate         timeutil.RFC3339YMDTime `json:"due_date,omitempty"`
	StartDate       timeutil.RFC3339YMDTime `json:"start_date,omitempty"`
	ReferencePrefix string                  `json:"referece_prefix,omitempty"`
}

func (f *InlineResponse200Features) Inflate() {
	f.ReferencePrefix = regexp.MustCompile(`-\d+$`).ReplaceAllString(f.ReferenceNum, "")
}
