/*
Aha.io API

Testing IdeasAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package aha

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/grokify/go-aha/v3/oag7/aha"
)

func Test_aha_IdeasAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test IdeasAPIService GetIdea", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ideaId string

		resp, httpRes, err := apiClient.IdeasAPI.GetIdea(context.Background(), ideaId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test IdeasAPIService ListIdeas", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.IdeasAPI.ListIdeas(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
