/*
Aha.io API

Testing WorkflowsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package aha

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/grokify/go-aha/v3/oag7/aha"
)

func Test_aha_WorkflowsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorkflowsAPIService ListProductWorkflows", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.WorkflowsAPI.ListProductWorkflows(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
