/*
Aha.io API

Testing FeaturesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package aha

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/grokify/go-aha/v3/oag7/aha"
)

func Test_aha_FeaturesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FeaturesAPIService CreateReleaseFeature", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var releaseId string

		resp, httpRes, err := apiClient.FeaturesAPI.CreateReleaseFeature(context.Background(), releaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeaturesAPIService GetFeature", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var featureId string

		resp, httpRes, err := apiClient.FeaturesAPI.GetFeature(context.Background(), featureId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeaturesAPIService ListFeatureIdeas", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var featureId string

		resp, httpRes, err := apiClient.FeaturesAPI.ListFeatureIdeas(context.Background(), featureId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeaturesAPIService ListFeatures", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FeaturesAPI.ListFeatures(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeaturesAPIService ListReleaseFeatures", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var releaseId string

		resp, httpRes, err := apiClient.FeaturesAPI.ListReleaseFeatures(context.Background(), releaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeaturesAPIService UpdateFeature", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var featureId string

		resp, httpRes, err := apiClient.FeaturesAPI.UpdateFeature(context.Background(), featureId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
