/*
Aha.io API

Testing StrategicModelsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package aha

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/grokify/go-aha/v3/oag7/aha"
)

func Test_aha_StrategicModelsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test StrategicModelsAPIService CreateProductStrategicModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.StrategicModelsAPI.CreateProductStrategicModel(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StrategicModelsAPIService GetStrategicModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var strategyModelId string

		resp, httpRes, err := apiClient.StrategicModelsAPI.GetStrategicModel(context.Background(), strategyModelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StrategicModelsAPIService ListProductStrategicModels", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var productId string

		resp, httpRes, err := apiClient.StrategicModelsAPI.ListProductStrategicModels(context.Background(), productId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StrategicModelsAPIService ListStrategicModels", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.StrategicModelsAPI.ListStrategicModels(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StrategicModelsAPIService UpdateStrategicModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var strategyModelId string

		resp, httpRes, err := apiClient.StrategicModelsAPI.UpdateStrategicModel(context.Background(), strategyModelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test StrategicModelsAPIService UpdateStrategicModelComponent", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var strategyModelId string
		var componentId string

		resp, httpRes, err := apiClient.StrategicModelsAPI.UpdateStrategicModelComponent(context.Background(), strategyModelId, componentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
