/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aha

// FeatureWrap struct for FeatureWrap
type FeatureWrap struct {
	Feature Feature `json:"feature,omitempty"`
}
