/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aha

// ProductsResponse struct for ProductsResponse
type ProductsResponse struct {
	Products   []ProductMeta `json:"products,omitempty"`
	Pagination Pagination    `json:"pagination,omitempty"`
}
