/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aha

// ProductResponse struct for ProductResponse
type ProductResponse struct {
	Product Product `json:"product,omitempty"`
}
