/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aha

import (
	"time"
)

// Product struct for Product
type Product struct {
	// A unique identifier for the product.
	Id string `json:"id,omitempty"`
	// The reference prefix slug for the product.
	ReferencePrefix string `json:"reference_prefix,omitempty"`
	// The name for the product.
	Name string `json:"name,omitempty"`
	// Whether the product is a product line or not.
	ProductLine bool `json:"product_line,omitempty"`
	// The date-time when the product was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The date-time when the product was updated.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// User URL for the project.
	Url string `json:"url,omitempty"`
	// User URL for the project.
	Resource string `json:"resource,omitempty"`
	// Whether the product has ideas or not.
	HasIdeas bool `json:"has_ideas,omitempty"`
	// Whether the product has master features or not.
	HasMasterFeatures bool `json:"has_master_features,omitempty"`
}
