/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aha

import (
	"time"
)

// ProductMeta struct for ProductMeta
type ProductMeta struct {
	// A unique identifier for the product.
	Id string `json:"id,omitempty"`
	// The reference prefix slug for the product.
	ReferencePrefix string `json:"reference_prefix,omitempty"`
	// The name for the product.
	Name string `json:"name,omitempty"`
	// Whether the product is a product line or not.
	ProductLine bool `json:"product_line,omitempty"`
	// The date-time when the product was created.
	CreatedAt time.Time `json:"created_at,omitempty"`
}
