/*
 * Aha.io API
 *
 * Articles that matter on social publishing platform
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package aha

// FeatureWorkflowStatus struct for FeatureWorkflowStatus
type FeatureWorkflowStatus struct {
	Id       string `json:"id,omitempty"`
	Name     string `json:"name,omitempty"`
	Position int64  `json:"position,omitempty"`
	Complete bool   `json:"complete,omitempty"`
	Color    string `json:"color,omitempty"`
}
