/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the IdeaOrganizationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdeaOrganizationsResponse{}

// IdeaOrganizationsResponse struct for IdeaOrganizationsResponse
type IdeaOrganizationsResponse struct {
	IdeaOrganizations    []IdeaOrganizationRef `json:"idea_organizations,omitempty"`
	Pagination           *Pagination           `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdeaOrganizationsResponse IdeaOrganizationsResponse

// NewIdeaOrganizationsResponse instantiates a new IdeaOrganizationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdeaOrganizationsResponse() *IdeaOrganizationsResponse {
	this := IdeaOrganizationsResponse{}
	return &this
}

// NewIdeaOrganizationsResponseWithDefaults instantiates a new IdeaOrganizationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdeaOrganizationsResponseWithDefaults() *IdeaOrganizationsResponse {
	this := IdeaOrganizationsResponse{}
	return &this
}

// GetIdeaOrganizations returns the IdeaOrganizations field value if set, zero value otherwise.
func (o *IdeaOrganizationsResponse) GetIdeaOrganizations() []IdeaOrganizationRef {
	if o == nil || IsNil(o.IdeaOrganizations) {
		var ret []IdeaOrganizationRef
		return ret
	}
	return o.IdeaOrganizations
}

// GetIdeaOrganizationsOk returns a tuple with the IdeaOrganizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganizationsResponse) GetIdeaOrganizationsOk() ([]IdeaOrganizationRef, bool) {
	if o == nil || IsNil(o.IdeaOrganizations) {
		return nil, false
	}
	return o.IdeaOrganizations, true
}

// HasIdeaOrganizations returns a boolean if a field has been set.
func (o *IdeaOrganizationsResponse) HasIdeaOrganizations() bool {
	if o != nil && !IsNil(o.IdeaOrganizations) {
		return true
	}

	return false
}

// SetIdeaOrganizations gets a reference to the given []IdeaOrganizationRef and assigns it to the IdeaOrganizations field.
func (o *IdeaOrganizationsResponse) SetIdeaOrganizations(v []IdeaOrganizationRef) {
	o.IdeaOrganizations = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *IdeaOrganizationsResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganizationsResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *IdeaOrganizationsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *IdeaOrganizationsResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o IdeaOrganizationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdeaOrganizationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdeaOrganizations) {
		toSerialize["idea_organizations"] = o.IdeaOrganizations
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdeaOrganizationsResponse) UnmarshalJSON(data []byte) (err error) {
	varIdeaOrganizationsResponse := _IdeaOrganizationsResponse{}

	err = json.Unmarshal(data, &varIdeaOrganizationsResponse)

	if err != nil {
		return err
	}

	*o = IdeaOrganizationsResponse(varIdeaOrganizationsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "idea_organizations")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdeaOrganizationsResponse struct {
	value *IdeaOrganizationsResponse
	isSet bool
}

func (v NullableIdeaOrganizationsResponse) Get() *IdeaOrganizationsResponse {
	return v.value
}

func (v *NullableIdeaOrganizationsResponse) Set(val *IdeaOrganizationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdeaOrganizationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdeaOrganizationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdeaOrganizationsResponse(val *IdeaOrganizationsResponse) *NullableIdeaOrganizationsResponse {
	return &NullableIdeaOrganizationsResponse{value: val, isSet: true}
}

func (v NullableIdeaOrganizationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdeaOrganizationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
