/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"fmt"
)

// checks if the ReleaseCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReleaseCreateRequest{}

// ReleaseCreateRequest struct for ReleaseCreateRequest
type ReleaseCreateRequest struct {
	Release              ReleaseCreate `json:"release"`
	AdditionalProperties map[string]interface{}
}

type _ReleaseCreateRequest ReleaseCreateRequest

// NewReleaseCreateRequest instantiates a new ReleaseCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReleaseCreateRequest(release ReleaseCreate) *ReleaseCreateRequest {
	this := ReleaseCreateRequest{}
	this.Release = release
	return &this
}

// NewReleaseCreateRequestWithDefaults instantiates a new ReleaseCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReleaseCreateRequestWithDefaults() *ReleaseCreateRequest {
	this := ReleaseCreateRequest{}
	return &this
}

// GetRelease returns the Release field value
func (o *ReleaseCreateRequest) GetRelease() ReleaseCreate {
	if o == nil {
		var ret ReleaseCreate
		return ret
	}

	return o.Release
}

// GetReleaseOk returns a tuple with the Release field value
// and a boolean to check if the value has been set.
func (o *ReleaseCreateRequest) GetReleaseOk() (*ReleaseCreate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Release, true
}

// SetRelease sets field value
func (o *ReleaseCreateRequest) SetRelease(v ReleaseCreate) {
	o.Release = v
}

func (o ReleaseCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReleaseCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["release"] = o.Release

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReleaseCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"release",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReleaseCreateRequest := _ReleaseCreateRequest{}

	err = json.Unmarshal(data, &varReleaseCreateRequest)

	if err != nil {
		return err
	}

	*o = ReleaseCreateRequest(varReleaseCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "release")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReleaseCreateRequest struct {
	value *ReleaseCreateRequest
	isSet bool
}

func (v NullableReleaseCreateRequest) Get() *ReleaseCreateRequest {
	return v.value
}

func (v *NullableReleaseCreateRequest) Set(val *ReleaseCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReleaseCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReleaseCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReleaseCreateRequest(val *ReleaseCreateRequest) *NullableReleaseCreateRequest {
	return &NullableReleaseCreateRequest{value: val, isSet: true}
}

func (v NullableReleaseCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReleaseCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
