/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the EpicsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EpicsResponse{}

// EpicsResponse struct for EpicsResponse
type EpicsResponse struct {
	Epics                []EpicMeta  `json:"epics,omitempty"`
	Pagination           *Pagination `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EpicsResponse EpicsResponse

// NewEpicsResponse instantiates a new EpicsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEpicsResponse() *EpicsResponse {
	this := EpicsResponse{}
	return &this
}

// NewEpicsResponseWithDefaults instantiates a new EpicsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEpicsResponseWithDefaults() *EpicsResponse {
	this := EpicsResponse{}
	return &this
}

// GetEpics returns the Epics field value if set, zero value otherwise.
func (o *EpicsResponse) GetEpics() []EpicMeta {
	if o == nil || IsNil(o.Epics) {
		var ret []EpicMeta
		return ret
	}
	return o.Epics
}

// GetEpicsOk returns a tuple with the Epics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EpicsResponse) GetEpicsOk() ([]EpicMeta, bool) {
	if o == nil || IsNil(o.Epics) {
		return nil, false
	}
	return o.Epics, true
}

// HasEpics returns a boolean if a field has been set.
func (o *EpicsResponse) HasEpics() bool {
	if o != nil && !IsNil(o.Epics) {
		return true
	}

	return false
}

// SetEpics gets a reference to the given []EpicMeta and assigns it to the Epics field.
func (o *EpicsResponse) SetEpics(v []EpicMeta) {
	o.Epics = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *EpicsResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EpicsResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *EpicsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *EpicsResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o EpicsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EpicsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Epics) {
		toSerialize["epics"] = o.Epics
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EpicsResponse) UnmarshalJSON(data []byte) (err error) {
	varEpicsResponse := _EpicsResponse{}

	err = json.Unmarshal(data, &varEpicsResponse)

	if err != nil {
		return err
	}

	*o = EpicsResponse(varEpicsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "epics")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEpicsResponse struct {
	value *EpicsResponse
	isSet bool
}

func (v NullableEpicsResponse) Get() *EpicsResponse {
	return v.value
}

func (v *NullableEpicsResponse) Set(val *EpicsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEpicsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEpicsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEpicsResponse(val *EpicsResponse) *NullableEpicsResponse {
	return &NullableEpicsResponse{value: val, isSet: true}
}

func (v NullableEpicsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEpicsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
