/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the StrategicModelComponentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategicModelComponentResponse{}

// StrategicModelComponentResponse struct for StrategicModelComponentResponse
type StrategicModelComponentResponse struct {
	Component            *StrategicModelComponent `json:"component,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StrategicModelComponentResponse StrategicModelComponentResponse

// NewStrategicModelComponentResponse instantiates a new StrategicModelComponentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategicModelComponentResponse() *StrategicModelComponentResponse {
	this := StrategicModelComponentResponse{}
	return &this
}

// NewStrategicModelComponentResponseWithDefaults instantiates a new StrategicModelComponentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategicModelComponentResponseWithDefaults() *StrategicModelComponentResponse {
	this := StrategicModelComponentResponse{}
	return &this
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *StrategicModelComponentResponse) GetComponent() StrategicModelComponent {
	if o == nil || IsNil(o.Component) {
		var ret StrategicModelComponent
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelComponentResponse) GetComponentOk() (*StrategicModelComponent, bool) {
	if o == nil || IsNil(o.Component) {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *StrategicModelComponentResponse) HasComponent() bool {
	if o != nil && !IsNil(o.Component) {
		return true
	}

	return false
}

// SetComponent gets a reference to the given StrategicModelComponent and assigns it to the Component field.
func (o *StrategicModelComponentResponse) SetComponent(v StrategicModelComponent) {
	o.Component = &v
}

func (o StrategicModelComponentResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategicModelComponentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Component) {
		toSerialize["component"] = o.Component
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrategicModelComponentResponse) UnmarshalJSON(data []byte) (err error) {
	varStrategicModelComponentResponse := _StrategicModelComponentResponse{}

	err = json.Unmarshal(data, &varStrategicModelComponentResponse)

	if err != nil {
		return err
	}

	*o = StrategicModelComponentResponse(varStrategicModelComponentResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "component")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrategicModelComponentResponse struct {
	value *StrategicModelComponentResponse
	isSet bool
}

func (v NullableStrategicModelComponentResponse) Get() *StrategicModelComponentResponse {
	return v.value
}

func (v *NullableStrategicModelComponentResponse) Set(val *StrategicModelComponentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategicModelComponentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategicModelComponentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategicModelComponentResponse(val *StrategicModelComponentResponse) *NullableStrategicModelComponentResponse {
	return &NullableStrategicModelComponentResponse{value: val, isSet: true}
}

func (v NullableStrategicModelComponentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategicModelComponentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
