/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the GoalsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoalsResponse{}

// GoalsResponse struct for GoalsResponse
type GoalsResponse struct {
	Goals                []GoalMeta  `json:"goals,omitempty"`
	Pagination           *Pagination `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GoalsResponse GoalsResponse

// NewGoalsResponse instantiates a new GoalsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoalsResponse() *GoalsResponse {
	this := GoalsResponse{}
	return &this
}

// NewGoalsResponseWithDefaults instantiates a new GoalsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoalsResponseWithDefaults() *GoalsResponse {
	this := GoalsResponse{}
	return &this
}

// GetGoals returns the Goals field value if set, zero value otherwise.
func (o *GoalsResponse) GetGoals() []GoalMeta {
	if o == nil || IsNil(o.Goals) {
		var ret []GoalMeta
		return ret
	}
	return o.Goals
}

// GetGoalsOk returns a tuple with the Goals field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoalsResponse) GetGoalsOk() ([]GoalMeta, bool) {
	if o == nil || IsNil(o.Goals) {
		return nil, false
	}
	return o.Goals, true
}

// HasGoals returns a boolean if a field has been set.
func (o *GoalsResponse) HasGoals() bool {
	if o != nil && !IsNil(o.Goals) {
		return true
	}

	return false
}

// SetGoals gets a reference to the given []GoalMeta and assigns it to the Goals field.
func (o *GoalsResponse) SetGoals(v []GoalMeta) {
	o.Goals = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *GoalsResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoalsResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *GoalsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *GoalsResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o GoalsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoalsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Goals) {
		toSerialize["goals"] = o.Goals
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GoalsResponse) UnmarshalJSON(data []byte) (err error) {
	varGoalsResponse := _GoalsResponse{}

	err = json.Unmarshal(data, &varGoalsResponse)

	if err != nil {
		return err
	}

	*o = GoalsResponse(varGoalsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "goals")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGoalsResponse struct {
	value *GoalsResponse
	isSet bool
}

func (v NullableGoalsResponse) Get() *GoalsResponse {
	return v.value
}

func (v *NullableGoalsResponse) Set(val *GoalsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGoalsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGoalsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoalsResponse(val *GoalsResponse) *NullableGoalsResponse {
	return &NullableGoalsResponse{value: val, isSet: true}
}

func (v NullableGoalsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoalsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
