/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the CustomFieldOption type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomFieldOption{}

// CustomFieldOption struct for CustomFieldOption
type CustomFieldOption struct {
	Id                   *string        `json:"id,omitempty"`
	Value                *string        `json:"value,omitempty"`
	Position             *int32         `json:"position,omitempty"`
	Color                NullableString `json:"color,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomFieldOption CustomFieldOption

// NewCustomFieldOption instantiates a new CustomFieldOption object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomFieldOption() *CustomFieldOption {
	this := CustomFieldOption{}
	return &this
}

// NewCustomFieldOptionWithDefaults instantiates a new CustomFieldOption object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomFieldOptionWithDefaults() *CustomFieldOption {
	this := CustomFieldOption{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustomFieldOption) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldOption) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustomFieldOption) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CustomFieldOption) SetId(v string) {
	o.Id = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *CustomFieldOption) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldOption) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *CustomFieldOption) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *CustomFieldOption) SetValue(v string) {
	o.Value = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *CustomFieldOption) GetPosition() int32 {
	if o == nil || IsNil(o.Position) {
		var ret int32
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldOption) GetPositionOk() (*int32, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *CustomFieldOption) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int32 and assigns it to the Position field.
func (o *CustomFieldOption) SetPosition(v int32) {
	o.Position = &v
}

// GetColor returns the Color field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CustomFieldOption) GetColor() string {
	if o == nil || IsNil(o.Color.Get()) {
		var ret string
		return ret
	}
	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomFieldOption) GetColorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// HasColor returns a boolean if a field has been set.
func (o *CustomFieldOption) HasColor() bool {
	if o != nil && o.Color.IsSet() {
		return true
	}

	return false
}

// SetColor gets a reference to the given NullableString and assigns it to the Color field.
func (o *CustomFieldOption) SetColor(v string) {
	o.Color.Set(&v)
}

// SetColorNil sets the value for Color to be an explicit nil
func (o *CustomFieldOption) SetColorNil() {
	o.Color.Set(nil)
}

// UnsetColor ensures that no value is present for Color, not even an explicit nil
func (o *CustomFieldOption) UnsetColor() {
	o.Color.Unset()
}

func (o CustomFieldOption) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomFieldOption) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if o.Color.IsSet() {
		toSerialize["color"] = o.Color.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomFieldOption) UnmarshalJSON(data []byte) (err error) {
	varCustomFieldOption := _CustomFieldOption{}

	err = json.Unmarshal(data, &varCustomFieldOption)

	if err != nil {
		return err
	}

	*o = CustomFieldOption(varCustomFieldOption)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "value")
		delete(additionalProperties, "position")
		delete(additionalProperties, "color")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomFieldOption struct {
	value *CustomFieldOption
	isSet bool
}

func (v NullableCustomFieldOption) Get() *CustomFieldOption {
	return v.value
}

func (v *NullableCustomFieldOption) Set(val *CustomFieldOption) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldOption) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldOption) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldOption(val *CustomFieldOption) *NullableCustomFieldOption {
	return &NullableCustomFieldOption{value: val, isSet: true}
}

func (v NullableCustomFieldOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldOption) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
