/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"fmt"
)

// checks if the EpicCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EpicCreateRequest{}

// EpicCreateRequest struct for EpicCreateRequest
type EpicCreateRequest struct {
	Epic                 EpicCreate `json:"epic"`
	AdditionalProperties map[string]interface{}
}

type _EpicCreateRequest EpicCreateRequest

// NewEpicCreateRequest instantiates a new EpicCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEpicCreateRequest(epic EpicCreate) *EpicCreateRequest {
	this := EpicCreateRequest{}
	this.Epic = epic
	return &this
}

// NewEpicCreateRequestWithDefaults instantiates a new EpicCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEpicCreateRequestWithDefaults() *EpicCreateRequest {
	this := EpicCreateRequest{}
	return &this
}

// GetEpic returns the Epic field value
func (o *EpicCreateRequest) GetEpic() EpicCreate {
	if o == nil {
		var ret EpicCreate
		return ret
	}

	return o.Epic
}

// GetEpicOk returns a tuple with the Epic field value
// and a boolean to check if the value has been set.
func (o *EpicCreateRequest) GetEpicOk() (*EpicCreate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Epic, true
}

// SetEpic sets field value
func (o *EpicCreateRequest) SetEpic(v EpicCreate) {
	o.Epic = v
}

func (o EpicCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EpicCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["epic"] = o.Epic

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EpicCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"epic",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEpicCreateRequest := _EpicCreateRequest{}

	err = json.Unmarshal(data, &varEpicCreateRequest)

	if err != nil {
		return err
	}

	*o = EpicCreateRequest(varEpicCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "epic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEpicCreateRequest struct {
	value *EpicCreateRequest
	isSet bool
}

func (v NullableEpicCreateRequest) Get() *EpicCreateRequest {
	return v.value
}

func (v *NullableEpicCreateRequest) Set(val *EpicCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEpicCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEpicCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEpicCreateRequest(val *EpicCreateRequest) *NullableEpicCreateRequest {
	return &NullableEpicCreateRequest{value: val, isSet: true}
}

func (v NullableEpicCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEpicCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
