/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the ProductUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductUpdate{}

// ProductUpdate struct for ProductUpdate
type ProductUpdate struct {
	// Name of the product
	Name *string `json:"name,omitempty"`
	// Abbreviation used as prefix on all features
	ReferencePrefix *string `json:"reference_prefix,omitempty"`
	// Description of the product (HTML allowed)
	Description *string `json:"description,omitempty"`
	// Numeric ID or prefix of parent product line
	ParentId *string `json:"parent_id,omitempty"`
	// Type of workspace
	WorkspaceType        *string `json:"workspace_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductUpdate ProductUpdate

// NewProductUpdate instantiates a new ProductUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductUpdate() *ProductUpdate {
	this := ProductUpdate{}
	return &this
}

// NewProductUpdateWithDefaults instantiates a new ProductUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductUpdateWithDefaults() *ProductUpdate {
	this := ProductUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProductUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProductUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProductUpdate) SetName(v string) {
	o.Name = &v
}

// GetReferencePrefix returns the ReferencePrefix field value if set, zero value otherwise.
func (o *ProductUpdate) GetReferencePrefix() string {
	if o == nil || IsNil(o.ReferencePrefix) {
		var ret string
		return ret
	}
	return *o.ReferencePrefix
}

// GetReferencePrefixOk returns a tuple with the ReferencePrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUpdate) GetReferencePrefixOk() (*string, bool) {
	if o == nil || IsNil(o.ReferencePrefix) {
		return nil, false
	}
	return o.ReferencePrefix, true
}

// HasReferencePrefix returns a boolean if a field has been set.
func (o *ProductUpdate) HasReferencePrefix() bool {
	if o != nil && !IsNil(o.ReferencePrefix) {
		return true
	}

	return false
}

// SetReferencePrefix gets a reference to the given string and assigns it to the ReferencePrefix field.
func (o *ProductUpdate) SetReferencePrefix(v string) {
	o.ReferencePrefix = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProductUpdate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProductUpdate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProductUpdate) SetDescription(v string) {
	o.Description = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *ProductUpdate) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUpdate) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *ProductUpdate) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *ProductUpdate) SetParentId(v string) {
	o.ParentId = &v
}

// GetWorkspaceType returns the WorkspaceType field value if set, zero value otherwise.
func (o *ProductUpdate) GetWorkspaceType() string {
	if o == nil || IsNil(o.WorkspaceType) {
		var ret string
		return ret
	}
	return *o.WorkspaceType
}

// GetWorkspaceTypeOk returns a tuple with the WorkspaceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductUpdate) GetWorkspaceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.WorkspaceType) {
		return nil, false
	}
	return o.WorkspaceType, true
}

// HasWorkspaceType returns a boolean if a field has been set.
func (o *ProductUpdate) HasWorkspaceType() bool {
	if o != nil && !IsNil(o.WorkspaceType) {
		return true
	}

	return false
}

// SetWorkspaceType gets a reference to the given string and assigns it to the WorkspaceType field.
func (o *ProductUpdate) SetWorkspaceType(v string) {
	o.WorkspaceType = &v
}

func (o ProductUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ReferencePrefix) {
		toSerialize["reference_prefix"] = o.ReferencePrefix
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}
	if !IsNil(o.WorkspaceType) {
		toSerialize["workspace_type"] = o.WorkspaceType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductUpdate) UnmarshalJSON(data []byte) (err error) {
	varProductUpdate := _ProductUpdate{}

	err = json.Unmarshal(data, &varProductUpdate)

	if err != nil {
		return err
	}

	*o = ProductUpdate(varProductUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "reference_prefix")
		delete(additionalProperties, "description")
		delete(additionalProperties, "parent_id")
		delete(additionalProperties, "workspace_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductUpdate struct {
	value *ProductUpdate
	isSet bool
}

func (v NullableProductUpdate) Get() *ProductUpdate {
	return v.value
}

func (v *NullableProductUpdate) Set(val *ProductUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableProductUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableProductUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductUpdate(val *ProductUpdate) *NullableProductUpdate {
	return &NullableProductUpdate{value: val, isSet: true}
}

func (v NullableProductUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
