/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the CustomFieldOptionListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomFieldOptionListResponse{}

// CustomFieldOptionListResponse struct for CustomFieldOptionListResponse
type CustomFieldOptionListResponse struct {
	CustomFieldOptions   []CustomFieldOption `json:"custom_field_options,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CustomFieldOptionListResponse CustomFieldOptionListResponse

// NewCustomFieldOptionListResponse instantiates a new CustomFieldOptionListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomFieldOptionListResponse() *CustomFieldOptionListResponse {
	this := CustomFieldOptionListResponse{}
	return &this
}

// NewCustomFieldOptionListResponseWithDefaults instantiates a new CustomFieldOptionListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomFieldOptionListResponseWithDefaults() *CustomFieldOptionListResponse {
	this := CustomFieldOptionListResponse{}
	return &this
}

// GetCustomFieldOptions returns the CustomFieldOptions field value if set, zero value otherwise.
func (o *CustomFieldOptionListResponse) GetCustomFieldOptions() []CustomFieldOption {
	if o == nil || IsNil(o.CustomFieldOptions) {
		var ret []CustomFieldOption
		return ret
	}
	return o.CustomFieldOptions
}

// GetCustomFieldOptionsOk returns a tuple with the CustomFieldOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldOptionListResponse) GetCustomFieldOptionsOk() ([]CustomFieldOption, bool) {
	if o == nil || IsNil(o.CustomFieldOptions) {
		return nil, false
	}
	return o.CustomFieldOptions, true
}

// HasCustomFieldOptions returns a boolean if a field has been set.
func (o *CustomFieldOptionListResponse) HasCustomFieldOptions() bool {
	if o != nil && !IsNil(o.CustomFieldOptions) {
		return true
	}

	return false
}

// SetCustomFieldOptions gets a reference to the given []CustomFieldOption and assigns it to the CustomFieldOptions field.
func (o *CustomFieldOptionListResponse) SetCustomFieldOptions(v []CustomFieldOption) {
	o.CustomFieldOptions = v
}

func (o CustomFieldOptionListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomFieldOptionListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomFieldOptions) {
		toSerialize["custom_field_options"] = o.CustomFieldOptions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomFieldOptionListResponse) UnmarshalJSON(data []byte) (err error) {
	varCustomFieldOptionListResponse := _CustomFieldOptionListResponse{}

	err = json.Unmarshal(data, &varCustomFieldOptionListResponse)

	if err != nil {
		return err
	}

	*o = CustomFieldOptionListResponse(varCustomFieldOptionListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "custom_field_options")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomFieldOptionListResponse struct {
	value *CustomFieldOptionListResponse
	isSet bool
}

func (v NullableCustomFieldOptionListResponse) Get() *CustomFieldOptionListResponse {
	return v.value
}

func (v *NullableCustomFieldOptionListResponse) Set(val *CustomFieldOptionListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldOptionListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldOptionListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldOptionListResponse(val *CustomFieldOptionListResponse) *NullableCustomFieldOptionListResponse {
	return &NullableCustomFieldOptionListResponse{value: val, isSet: true}
}

func (v NullableCustomFieldOptionListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldOptionListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
