/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"fmt"
)

// checks if the StrategicModelCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategicModelCreateRequest{}

// StrategicModelCreateRequest struct for StrategicModelCreateRequest
type StrategicModelCreateRequest struct {
	StrategyModel        StrategicModelCreate `json:"strategy_model"`
	AdditionalProperties map[string]interface{}
}

type _StrategicModelCreateRequest StrategicModelCreateRequest

// NewStrategicModelCreateRequest instantiates a new StrategicModelCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategicModelCreateRequest(strategyModel StrategicModelCreate) *StrategicModelCreateRequest {
	this := StrategicModelCreateRequest{}
	this.StrategyModel = strategyModel
	return &this
}

// NewStrategicModelCreateRequestWithDefaults instantiates a new StrategicModelCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategicModelCreateRequestWithDefaults() *StrategicModelCreateRequest {
	this := StrategicModelCreateRequest{}
	return &this
}

// GetStrategyModel returns the StrategyModel field value
func (o *StrategicModelCreateRequest) GetStrategyModel() StrategicModelCreate {
	if o == nil {
		var ret StrategicModelCreate
		return ret
	}

	return o.StrategyModel
}

// GetStrategyModelOk returns a tuple with the StrategyModel field value
// and a boolean to check if the value has been set.
func (o *StrategicModelCreateRequest) GetStrategyModelOk() (*StrategicModelCreate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StrategyModel, true
}

// SetStrategyModel sets field value
func (o *StrategicModelCreateRequest) SetStrategyModel(v StrategicModelCreate) {
	o.StrategyModel = v
}

func (o StrategicModelCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategicModelCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["strategy_model"] = o.StrategyModel

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrategicModelCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"strategy_model",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrategicModelCreateRequest := _StrategicModelCreateRequest{}

	err = json.Unmarshal(data, &varStrategicModelCreateRequest)

	if err != nil {
		return err
	}

	*o = StrategicModelCreateRequest(varStrategicModelCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "strategy_model")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrategicModelCreateRequest struct {
	value *StrategicModelCreateRequest
	isSet bool
}

func (v NullableStrategicModelCreateRequest) Get() *StrategicModelCreateRequest {
	return v.value
}

func (v *NullableStrategicModelCreateRequest) Set(val *StrategicModelCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategicModelCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategicModelCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategicModelCreateRequest(val *StrategicModelCreateRequest) *NullableStrategicModelCreateRequest {
	return &NullableStrategicModelCreateRequest{value: val, isSet: true}
}

func (v NullableStrategicModelCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategicModelCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
