/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the ReleaseUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReleaseUpdate{}

// ReleaseUpdate struct for ReleaseUpdate
type ReleaseUpdate struct {
	Name                 *string        `json:"name,omitempty"`
	StartDate            NullableString `json:"start_date,omitempty"`
	ReleaseDate          NullableString `json:"release_date,omitempty"`
	ExternalReleaseDate  NullableString `json:"external_release_date,omitempty"`
	DevelopmentStartedOn *string        `json:"development_started_on,omitempty"`
	ParkingLot           *bool          `json:"parking_lot,omitempty"`
	// Theme of the release (may include HTML formatting). Also shown as the release description in the Aha! UI.
	Theme          *string  `json:"theme,omitempty"`
	ProgressSource *string  `json:"progress_source,omitempty"`
	Progress       *float64 `json:"progress,omitempty"`
	// Workflow status ID or name. Transitioning to the status the product's workflow defines as \"released\" is how a release becomes Released.
	WorkflowStatus       *string `json:"workflow_status,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReleaseUpdate ReleaseUpdate

// NewReleaseUpdate instantiates a new ReleaseUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReleaseUpdate() *ReleaseUpdate {
	this := ReleaseUpdate{}
	return &this
}

// NewReleaseUpdateWithDefaults instantiates a new ReleaseUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReleaseUpdateWithDefaults() *ReleaseUpdate {
	this := ReleaseUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ReleaseUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ReleaseUpdate) SetName(v string) {
	o.Name = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseUpdate) GetStartDate() string {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret string
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseUpdate) GetStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableString and assigns it to the StartDate field.
func (o *ReleaseUpdate) SetStartDate(v string) {
	o.StartDate.Set(&v)
}

// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *ReleaseUpdate) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *ReleaseUpdate) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetReleaseDate returns the ReleaseDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseUpdate) GetReleaseDate() string {
	if o == nil || IsNil(o.ReleaseDate.Get()) {
		var ret string
		return ret
	}
	return *o.ReleaseDate.Get()
}

// GetReleaseDateOk returns a tuple with the ReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseUpdate) GetReleaseDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReleaseDate.Get(), o.ReleaseDate.IsSet()
}

// HasReleaseDate returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasReleaseDate() bool {
	if o != nil && o.ReleaseDate.IsSet() {
		return true
	}

	return false
}

// SetReleaseDate gets a reference to the given NullableString and assigns it to the ReleaseDate field.
func (o *ReleaseUpdate) SetReleaseDate(v string) {
	o.ReleaseDate.Set(&v)
}

// SetReleaseDateNil sets the value for ReleaseDate to be an explicit nil
func (o *ReleaseUpdate) SetReleaseDateNil() {
	o.ReleaseDate.Set(nil)
}

// UnsetReleaseDate ensures that no value is present for ReleaseDate, not even an explicit nil
func (o *ReleaseUpdate) UnsetReleaseDate() {
	o.ReleaseDate.Unset()
}

// GetExternalReleaseDate returns the ExternalReleaseDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ReleaseUpdate) GetExternalReleaseDate() string {
	if o == nil || IsNil(o.ExternalReleaseDate.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalReleaseDate.Get()
}

// GetExternalReleaseDateOk returns a tuple with the ExternalReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ReleaseUpdate) GetExternalReleaseDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalReleaseDate.Get(), o.ExternalReleaseDate.IsSet()
}

// HasExternalReleaseDate returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasExternalReleaseDate() bool {
	if o != nil && o.ExternalReleaseDate.IsSet() {
		return true
	}

	return false
}

// SetExternalReleaseDate gets a reference to the given NullableString and assigns it to the ExternalReleaseDate field.
func (o *ReleaseUpdate) SetExternalReleaseDate(v string) {
	o.ExternalReleaseDate.Set(&v)
}

// SetExternalReleaseDateNil sets the value for ExternalReleaseDate to be an explicit nil
func (o *ReleaseUpdate) SetExternalReleaseDateNil() {
	o.ExternalReleaseDate.Set(nil)
}

// UnsetExternalReleaseDate ensures that no value is present for ExternalReleaseDate, not even an explicit nil
func (o *ReleaseUpdate) UnsetExternalReleaseDate() {
	o.ExternalReleaseDate.Unset()
}

// GetDevelopmentStartedOn returns the DevelopmentStartedOn field value if set, zero value otherwise.
func (o *ReleaseUpdate) GetDevelopmentStartedOn() string {
	if o == nil || IsNil(o.DevelopmentStartedOn) {
		var ret string
		return ret
	}
	return *o.DevelopmentStartedOn
}

// GetDevelopmentStartedOnOk returns a tuple with the DevelopmentStartedOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseUpdate) GetDevelopmentStartedOnOk() (*string, bool) {
	if o == nil || IsNil(o.DevelopmentStartedOn) {
		return nil, false
	}
	return o.DevelopmentStartedOn, true
}

// HasDevelopmentStartedOn returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasDevelopmentStartedOn() bool {
	if o != nil && !IsNil(o.DevelopmentStartedOn) {
		return true
	}

	return false
}

// SetDevelopmentStartedOn gets a reference to the given string and assigns it to the DevelopmentStartedOn field.
func (o *ReleaseUpdate) SetDevelopmentStartedOn(v string) {
	o.DevelopmentStartedOn = &v
}

// GetParkingLot returns the ParkingLot field value if set, zero value otherwise.
func (o *ReleaseUpdate) GetParkingLot() bool {
	if o == nil || IsNil(o.ParkingLot) {
		var ret bool
		return ret
	}
	return *o.ParkingLot
}

// GetParkingLotOk returns a tuple with the ParkingLot field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseUpdate) GetParkingLotOk() (*bool, bool) {
	if o == nil || IsNil(o.ParkingLot) {
		return nil, false
	}
	return o.ParkingLot, true
}

// HasParkingLot returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasParkingLot() bool {
	if o != nil && !IsNil(o.ParkingLot) {
		return true
	}

	return false
}

// SetParkingLot gets a reference to the given bool and assigns it to the ParkingLot field.
func (o *ReleaseUpdate) SetParkingLot(v bool) {
	o.ParkingLot = &v
}

// GetTheme returns the Theme field value if set, zero value otherwise.
func (o *ReleaseUpdate) GetTheme() string {
	if o == nil || IsNil(o.Theme) {
		var ret string
		return ret
	}
	return *o.Theme
}

// GetThemeOk returns a tuple with the Theme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseUpdate) GetThemeOk() (*string, bool) {
	if o == nil || IsNil(o.Theme) {
		return nil, false
	}
	return o.Theme, true
}

// HasTheme returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasTheme() bool {
	if o != nil && !IsNil(o.Theme) {
		return true
	}

	return false
}

// SetTheme gets a reference to the given string and assigns it to the Theme field.
func (o *ReleaseUpdate) SetTheme(v string) {
	o.Theme = &v
}

// GetProgressSource returns the ProgressSource field value if set, zero value otherwise.
func (o *ReleaseUpdate) GetProgressSource() string {
	if o == nil || IsNil(o.ProgressSource) {
		var ret string
		return ret
	}
	return *o.ProgressSource
}

// GetProgressSourceOk returns a tuple with the ProgressSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseUpdate) GetProgressSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ProgressSource) {
		return nil, false
	}
	return o.ProgressSource, true
}

// HasProgressSource returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasProgressSource() bool {
	if o != nil && !IsNil(o.ProgressSource) {
		return true
	}

	return false
}

// SetProgressSource gets a reference to the given string and assigns it to the ProgressSource field.
func (o *ReleaseUpdate) SetProgressSource(v string) {
	o.ProgressSource = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *ReleaseUpdate) GetProgress() float64 {
	if o == nil || IsNil(o.Progress) {
		var ret float64
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseUpdate) GetProgressOk() (*float64, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given float64 and assigns it to the Progress field.
func (o *ReleaseUpdate) SetProgress(v float64) {
	o.Progress = &v
}

// GetWorkflowStatus returns the WorkflowStatus field value if set, zero value otherwise.
func (o *ReleaseUpdate) GetWorkflowStatus() string {
	if o == nil || IsNil(o.WorkflowStatus) {
		var ret string
		return ret
	}
	return *o.WorkflowStatus
}

// GetWorkflowStatusOk returns a tuple with the WorkflowStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReleaseUpdate) GetWorkflowStatusOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowStatus) {
		return nil, false
	}
	return o.WorkflowStatus, true
}

// HasWorkflowStatus returns a boolean if a field has been set.
func (o *ReleaseUpdate) HasWorkflowStatus() bool {
	if o != nil && !IsNil(o.WorkflowStatus) {
		return true
	}

	return false
}

// SetWorkflowStatus gets a reference to the given string and assigns it to the WorkflowStatus field.
func (o *ReleaseUpdate) SetWorkflowStatus(v string) {
	o.WorkflowStatus = &v
}

func (o ReleaseUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReleaseUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.StartDate.IsSet() {
		toSerialize["start_date"] = o.StartDate.Get()
	}
	if o.ReleaseDate.IsSet() {
		toSerialize["release_date"] = o.ReleaseDate.Get()
	}
	if o.ExternalReleaseDate.IsSet() {
		toSerialize["external_release_date"] = o.ExternalReleaseDate.Get()
	}
	if !IsNil(o.DevelopmentStartedOn) {
		toSerialize["development_started_on"] = o.DevelopmentStartedOn
	}
	if !IsNil(o.ParkingLot) {
		toSerialize["parking_lot"] = o.ParkingLot
	}
	if !IsNil(o.Theme) {
		toSerialize["theme"] = o.Theme
	}
	if !IsNil(o.ProgressSource) {
		toSerialize["progress_source"] = o.ProgressSource
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.WorkflowStatus) {
		toSerialize["workflow_status"] = o.WorkflowStatus
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReleaseUpdate) UnmarshalJSON(data []byte) (err error) {
	varReleaseUpdate := _ReleaseUpdate{}

	err = json.Unmarshal(data, &varReleaseUpdate)

	if err != nil {
		return err
	}

	*o = ReleaseUpdate(varReleaseUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "start_date")
		delete(additionalProperties, "release_date")
		delete(additionalProperties, "external_release_date")
		delete(additionalProperties, "development_started_on")
		delete(additionalProperties, "parking_lot")
		delete(additionalProperties, "theme")
		delete(additionalProperties, "progress_source")
		delete(additionalProperties, "progress")
		delete(additionalProperties, "workflow_status")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReleaseUpdate struct {
	value *ReleaseUpdate
	isSet bool
}

func (v NullableReleaseUpdate) Get() *ReleaseUpdate {
	return v.value
}

func (v *NullableReleaseUpdate) Set(val *ReleaseUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableReleaseUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableReleaseUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReleaseUpdate(val *ReleaseUpdate) *NullableReleaseUpdate {
	return &NullableReleaseUpdate{value: val, isSet: true}
}

func (v NullableReleaseUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReleaseUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
