/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the StrategicModelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategicModelResponse{}

// StrategicModelResponse struct for StrategicModelResponse
type StrategicModelResponse struct {
	StrategyModel        *StrategicModel `json:"strategy_model,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StrategicModelResponse StrategicModelResponse

// NewStrategicModelResponse instantiates a new StrategicModelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategicModelResponse() *StrategicModelResponse {
	this := StrategicModelResponse{}
	return &this
}

// NewStrategicModelResponseWithDefaults instantiates a new StrategicModelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategicModelResponseWithDefaults() *StrategicModelResponse {
	this := StrategicModelResponse{}
	return &this
}

// GetStrategyModel returns the StrategyModel field value if set, zero value otherwise.
func (o *StrategicModelResponse) GetStrategyModel() StrategicModel {
	if o == nil || IsNil(o.StrategyModel) {
		var ret StrategicModel
		return ret
	}
	return *o.StrategyModel
}

// GetStrategyModelOk returns a tuple with the StrategyModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelResponse) GetStrategyModelOk() (*StrategicModel, bool) {
	if o == nil || IsNil(o.StrategyModel) {
		return nil, false
	}
	return o.StrategyModel, true
}

// HasStrategyModel returns a boolean if a field has been set.
func (o *StrategicModelResponse) HasStrategyModel() bool {
	if o != nil && !IsNil(o.StrategyModel) {
		return true
	}

	return false
}

// SetStrategyModel gets a reference to the given StrategicModel and assigns it to the StrategyModel field.
func (o *StrategicModelResponse) SetStrategyModel(v StrategicModel) {
	o.StrategyModel = &v
}

func (o StrategicModelResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategicModelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StrategyModel) {
		toSerialize["strategy_model"] = o.StrategyModel
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrategicModelResponse) UnmarshalJSON(data []byte) (err error) {
	varStrategicModelResponse := _StrategicModelResponse{}

	err = json.Unmarshal(data, &varStrategicModelResponse)

	if err != nil {
		return err
	}

	*o = StrategicModelResponse(varStrategicModelResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "strategy_model")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrategicModelResponse struct {
	value *StrategicModelResponse
	isSet bool
}

func (v NullableStrategicModelResponse) Get() *StrategicModelResponse {
	return v.value
}

func (v *NullableStrategicModelResponse) Set(val *StrategicModelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategicModelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategicModelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategicModelResponse(val *StrategicModelResponse) *NullableStrategicModelResponse {
	return &NullableStrategicModelResponse{value: val, isSet: true}
}

func (v NullableStrategicModelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategicModelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
