/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the CustomFieldDefinitionListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomFieldDefinitionListResponse{}

// CustomFieldDefinitionListResponse struct for CustomFieldDefinitionListResponse
type CustomFieldDefinitionListResponse struct {
	CustomFieldDefinitions []CustomFieldDefinition `json:"custom_field_definitions,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _CustomFieldDefinitionListResponse CustomFieldDefinitionListResponse

// NewCustomFieldDefinitionListResponse instantiates a new CustomFieldDefinitionListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomFieldDefinitionListResponse() *CustomFieldDefinitionListResponse {
	this := CustomFieldDefinitionListResponse{}
	return &this
}

// NewCustomFieldDefinitionListResponseWithDefaults instantiates a new CustomFieldDefinitionListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomFieldDefinitionListResponseWithDefaults() *CustomFieldDefinitionListResponse {
	this := CustomFieldDefinitionListResponse{}
	return &this
}

// GetCustomFieldDefinitions returns the CustomFieldDefinitions field value if set, zero value otherwise.
func (o *CustomFieldDefinitionListResponse) GetCustomFieldDefinitions() []CustomFieldDefinition {
	if o == nil || IsNil(o.CustomFieldDefinitions) {
		var ret []CustomFieldDefinition
		return ret
	}
	return o.CustomFieldDefinitions
}

// GetCustomFieldDefinitionsOk returns a tuple with the CustomFieldDefinitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomFieldDefinitionListResponse) GetCustomFieldDefinitionsOk() ([]CustomFieldDefinition, bool) {
	if o == nil || IsNil(o.CustomFieldDefinitions) {
		return nil, false
	}
	return o.CustomFieldDefinitions, true
}

// HasCustomFieldDefinitions returns a boolean if a field has been set.
func (o *CustomFieldDefinitionListResponse) HasCustomFieldDefinitions() bool {
	if o != nil && !IsNil(o.CustomFieldDefinitions) {
		return true
	}

	return false
}

// SetCustomFieldDefinitions gets a reference to the given []CustomFieldDefinition and assigns it to the CustomFieldDefinitions field.
func (o *CustomFieldDefinitionListResponse) SetCustomFieldDefinitions(v []CustomFieldDefinition) {
	o.CustomFieldDefinitions = v
}

func (o CustomFieldDefinitionListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomFieldDefinitionListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomFieldDefinitions) {
		toSerialize["custom_field_definitions"] = o.CustomFieldDefinitions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CustomFieldDefinitionListResponse) UnmarshalJSON(data []byte) (err error) {
	varCustomFieldDefinitionListResponse := _CustomFieldDefinitionListResponse{}

	err = json.Unmarshal(data, &varCustomFieldDefinitionListResponse)

	if err != nil {
		return err
	}

	*o = CustomFieldDefinitionListResponse(varCustomFieldDefinitionListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "custom_field_definitions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCustomFieldDefinitionListResponse struct {
	value *CustomFieldDefinitionListResponse
	isSet bool
}

func (v NullableCustomFieldDefinitionListResponse) Get() *CustomFieldDefinitionListResponse {
	return v.value
}

func (v *NullableCustomFieldDefinitionListResponse) Set(val *CustomFieldDefinitionListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomFieldDefinitionListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomFieldDefinitionListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomFieldDefinitionListResponse(val *CustomFieldDefinitionListResponse) *NullableCustomFieldDefinitionListResponse {
	return &NullableCustomFieldDefinitionListResponse{value: val, isSet: true}
}

func (v NullableCustomFieldDefinitionListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomFieldDefinitionListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
