/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the Epic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Epic{}

// Epic struct for Epic
type Epic struct {
	Id           string             `json:"id"`
	ReferenceNum string             `json:"reference_num"`
	Name         string             `json:"name"`
	Description  *DescriptionObject `json:"description,omitempty"`
	// Progress percentage (0-100)
	Progress NullableFloat32 `json:"progress,omitempty"`
	// Source of progress calculation
	ProgressSource *string        `json:"progress_source,omitempty"`
	StartDate      NullableString `json:"start_date,omitempty"`
	DueDate        NullableString `json:"due_date,omitempty"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      *time.Time     `json:"updated_at,omitempty"`
	// Web UI URL
	Url *string `json:"url,omitempty"`
	// API URL
	Resource             *string         `json:"resource,omitempty"`
	CommentsCount        *int64          `json:"comments_count,omitempty"`
	Position             *int64          `json:"position,omitempty"`
	Color                *string         `json:"color,omitempty"`
	WorkflowStatus       *WorkflowStatus `json:"workflow_status,omitempty"`
	Release              *Release        `json:"release,omitempty"`
	Initiative           *InitiativeMeta `json:"initiative,omitempty"`
	Tags                 []string        `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Epic Epic

// NewEpic instantiates a new Epic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEpic(id string, referenceNum string, name string, createdAt time.Time) *Epic {
	this := Epic{}
	this.Id = id
	this.ReferenceNum = referenceNum
	this.Name = name
	this.CreatedAt = createdAt
	return &this
}

// NewEpicWithDefaults instantiates a new Epic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEpicWithDefaults() *Epic {
	this := Epic{}
	return &this
}

// GetId returns the Id field value
func (o *Epic) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Epic) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Epic) SetId(v string) {
	o.Id = v
}

// GetReferenceNum returns the ReferenceNum field value
func (o *Epic) GetReferenceNum() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceNum
}

// GetReferenceNumOk returns a tuple with the ReferenceNum field value
// and a boolean to check if the value has been set.
func (o *Epic) GetReferenceNumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceNum, true
}

// SetReferenceNum sets field value
func (o *Epic) SetReferenceNum(v string) {
	o.ReferenceNum = v
}

// GetName returns the Name field value
func (o *Epic) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Epic) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Epic) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Epic) GetDescription() DescriptionObject {
	if o == nil || IsNil(o.Description) {
		var ret DescriptionObject
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetDescriptionOk() (*DescriptionObject, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Epic) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given DescriptionObject and assigns it to the Description field.
func (o *Epic) SetDescription(v DescriptionObject) {
	o.Description = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Epic) GetProgress() float32 {
	if o == nil || IsNil(o.Progress.Get()) {
		var ret float32
		return ret
	}
	return *o.Progress.Get()
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Epic) GetProgressOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Progress.Get(), o.Progress.IsSet()
}

// HasProgress returns a boolean if a field has been set.
func (o *Epic) HasProgress() bool {
	if o != nil && o.Progress.IsSet() {
		return true
	}

	return false
}

// SetProgress gets a reference to the given NullableFloat32 and assigns it to the Progress field.
func (o *Epic) SetProgress(v float32) {
	o.Progress.Set(&v)
}

// SetProgressNil sets the value for Progress to be an explicit nil
func (o *Epic) SetProgressNil() {
	o.Progress.Set(nil)
}

// UnsetProgress ensures that no value is present for Progress, not even an explicit nil
func (o *Epic) UnsetProgress() {
	o.Progress.Unset()
}

// GetProgressSource returns the ProgressSource field value if set, zero value otherwise.
func (o *Epic) GetProgressSource() string {
	if o == nil || IsNil(o.ProgressSource) {
		var ret string
		return ret
	}
	return *o.ProgressSource
}

// GetProgressSourceOk returns a tuple with the ProgressSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetProgressSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ProgressSource) {
		return nil, false
	}
	return o.ProgressSource, true
}

// HasProgressSource returns a boolean if a field has been set.
func (o *Epic) HasProgressSource() bool {
	if o != nil && !IsNil(o.ProgressSource) {
		return true
	}

	return false
}

// SetProgressSource gets a reference to the given string and assigns it to the ProgressSource field.
func (o *Epic) SetProgressSource(v string) {
	o.ProgressSource = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Epic) GetStartDate() string {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret string
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Epic) GetStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *Epic) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableString and assigns it to the StartDate field.
func (o *Epic) SetStartDate(v string) {
	o.StartDate.Set(&v)
}

// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *Epic) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *Epic) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetDueDate returns the DueDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Epic) GetDueDate() string {
	if o == nil || IsNil(o.DueDate.Get()) {
		var ret string
		return ret
	}
	return *o.DueDate.Get()
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Epic) GetDueDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DueDate.Get(), o.DueDate.IsSet()
}

// HasDueDate returns a boolean if a field has been set.
func (o *Epic) HasDueDate() bool {
	if o != nil && o.DueDate.IsSet() {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given NullableString and assigns it to the DueDate field.
func (o *Epic) SetDueDate(v string) {
	o.DueDate.Set(&v)
}

// SetDueDateNil sets the value for DueDate to be an explicit nil
func (o *Epic) SetDueDateNil() {
	o.DueDate.Set(nil)
}

// UnsetDueDate ensures that no value is present for DueDate, not even an explicit nil
func (o *Epic) UnsetDueDate() {
	o.DueDate.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *Epic) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Epic) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Epic) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Epic) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Epic) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *Epic) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Epic) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Epic) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Epic) SetUrl(v string) {
	o.Url = &v
}

// GetResource returns the Resource field value if set, zero value otherwise.
func (o *Epic) GetResource() string {
	if o == nil || IsNil(o.Resource) {
		var ret string
		return ret
	}
	return *o.Resource
}

// GetResourceOk returns a tuple with the Resource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetResourceOk() (*string, bool) {
	if o == nil || IsNil(o.Resource) {
		return nil, false
	}
	return o.Resource, true
}

// HasResource returns a boolean if a field has been set.
func (o *Epic) HasResource() bool {
	if o != nil && !IsNil(o.Resource) {
		return true
	}

	return false
}

// SetResource gets a reference to the given string and assigns it to the Resource field.
func (o *Epic) SetResource(v string) {
	o.Resource = &v
}

// GetCommentsCount returns the CommentsCount field value if set, zero value otherwise.
func (o *Epic) GetCommentsCount() int64 {
	if o == nil || IsNil(o.CommentsCount) {
		var ret int64
		return ret
	}
	return *o.CommentsCount
}

// GetCommentsCountOk returns a tuple with the CommentsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetCommentsCountOk() (*int64, bool) {
	if o == nil || IsNil(o.CommentsCount) {
		return nil, false
	}
	return o.CommentsCount, true
}

// HasCommentsCount returns a boolean if a field has been set.
func (o *Epic) HasCommentsCount() bool {
	if o != nil && !IsNil(o.CommentsCount) {
		return true
	}

	return false
}

// SetCommentsCount gets a reference to the given int64 and assigns it to the CommentsCount field.
func (o *Epic) SetCommentsCount(v int64) {
	o.CommentsCount = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *Epic) GetPosition() int64 {
	if o == nil || IsNil(o.Position) {
		var ret int64
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetPositionOk() (*int64, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *Epic) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int64 and assigns it to the Position field.
func (o *Epic) SetPosition(v int64) {
	o.Position = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *Epic) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *Epic) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *Epic) SetColor(v string) {
	o.Color = &v
}

// GetWorkflowStatus returns the WorkflowStatus field value if set, zero value otherwise.
func (o *Epic) GetWorkflowStatus() WorkflowStatus {
	if o == nil || IsNil(o.WorkflowStatus) {
		var ret WorkflowStatus
		return ret
	}
	return *o.WorkflowStatus
}

// GetWorkflowStatusOk returns a tuple with the WorkflowStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetWorkflowStatusOk() (*WorkflowStatus, bool) {
	if o == nil || IsNil(o.WorkflowStatus) {
		return nil, false
	}
	return o.WorkflowStatus, true
}

// HasWorkflowStatus returns a boolean if a field has been set.
func (o *Epic) HasWorkflowStatus() bool {
	if o != nil && !IsNil(o.WorkflowStatus) {
		return true
	}

	return false
}

// SetWorkflowStatus gets a reference to the given WorkflowStatus and assigns it to the WorkflowStatus field.
func (o *Epic) SetWorkflowStatus(v WorkflowStatus) {
	o.WorkflowStatus = &v
}

// GetRelease returns the Release field value if set, zero value otherwise.
func (o *Epic) GetRelease() Release {
	if o == nil || IsNil(o.Release) {
		var ret Release
		return ret
	}
	return *o.Release
}

// GetReleaseOk returns a tuple with the Release field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetReleaseOk() (*Release, bool) {
	if o == nil || IsNil(o.Release) {
		return nil, false
	}
	return o.Release, true
}

// HasRelease returns a boolean if a field has been set.
func (o *Epic) HasRelease() bool {
	if o != nil && !IsNil(o.Release) {
		return true
	}

	return false
}

// SetRelease gets a reference to the given Release and assigns it to the Release field.
func (o *Epic) SetRelease(v Release) {
	o.Release = &v
}

// GetInitiative returns the Initiative field value if set, zero value otherwise.
func (o *Epic) GetInitiative() InitiativeMeta {
	if o == nil || IsNil(o.Initiative) {
		var ret InitiativeMeta
		return ret
	}
	return *o.Initiative
}

// GetInitiativeOk returns a tuple with the Initiative field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetInitiativeOk() (*InitiativeMeta, bool) {
	if o == nil || IsNil(o.Initiative) {
		return nil, false
	}
	return o.Initiative, true
}

// HasInitiative returns a boolean if a field has been set.
func (o *Epic) HasInitiative() bool {
	if o != nil && !IsNil(o.Initiative) {
		return true
	}

	return false
}

// SetInitiative gets a reference to the given InitiativeMeta and assigns it to the Initiative field.
func (o *Epic) SetInitiative(v InitiativeMeta) {
	o.Initiative = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Epic) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Epic) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Epic) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Epic) SetTags(v []string) {
	o.Tags = v
}

func (o Epic) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Epic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["reference_num"] = o.ReferenceNum
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Progress.IsSet() {
		toSerialize["progress"] = o.Progress.Get()
	}
	if !IsNil(o.ProgressSource) {
		toSerialize["progress_source"] = o.ProgressSource
	}
	if o.StartDate.IsSet() {
		toSerialize["start_date"] = o.StartDate.Get()
	}
	if o.DueDate.IsSet() {
		toSerialize["due_date"] = o.DueDate.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Resource) {
		toSerialize["resource"] = o.Resource
	}
	if !IsNil(o.CommentsCount) {
		toSerialize["comments_count"] = o.CommentsCount
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.WorkflowStatus) {
		toSerialize["workflow_status"] = o.WorkflowStatus
	}
	if !IsNil(o.Release) {
		toSerialize["release"] = o.Release
	}
	if !IsNil(o.Initiative) {
		toSerialize["initiative"] = o.Initiative
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Epic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"reference_num",
		"name",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEpic := _Epic{}

	err = json.Unmarshal(data, &varEpic)

	if err != nil {
		return err
	}

	*o = Epic(varEpic)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "reference_num")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "progress")
		delete(additionalProperties, "progress_source")
		delete(additionalProperties, "start_date")
		delete(additionalProperties, "due_date")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "url")
		delete(additionalProperties, "resource")
		delete(additionalProperties, "comments_count")
		delete(additionalProperties, "position")
		delete(additionalProperties, "color")
		delete(additionalProperties, "workflow_status")
		delete(additionalProperties, "release")
		delete(additionalProperties, "initiative")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEpic struct {
	value *Epic
	isSet bool
}

func (v NullableEpic) Get() *Epic {
	return v.value
}

func (v *NullableEpic) Set(val *Epic) {
	v.value = val
	v.isSet = true
}

func (v NullableEpic) IsSet() bool {
	return v.isSet
}

func (v *NullableEpic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEpic(val *Epic) *NullableEpic {
	return &NullableEpic{value: val, isSet: true}
}

func (v NullableEpic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEpic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
