/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"fmt"
)

// checks if the FeatureCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureCreateRequest{}

// FeatureCreateRequest struct for FeatureCreateRequest
type FeatureCreateRequest struct {
	Feature              FeatureCreate `json:"feature"`
	AdditionalProperties map[string]interface{}
}

type _FeatureCreateRequest FeatureCreateRequest

// NewFeatureCreateRequest instantiates a new FeatureCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureCreateRequest(feature FeatureCreate) *FeatureCreateRequest {
	this := FeatureCreateRequest{}
	this.Feature = feature
	return &this
}

// NewFeatureCreateRequestWithDefaults instantiates a new FeatureCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureCreateRequestWithDefaults() *FeatureCreateRequest {
	this := FeatureCreateRequest{}
	return &this
}

// GetFeature returns the Feature field value
func (o *FeatureCreateRequest) GetFeature() FeatureCreate {
	if o == nil {
		var ret FeatureCreate
		return ret
	}

	return o.Feature
}

// GetFeatureOk returns a tuple with the Feature field value
// and a boolean to check if the value has been set.
func (o *FeatureCreateRequest) GetFeatureOk() (*FeatureCreate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Feature, true
}

// SetFeature sets field value
func (o *FeatureCreateRequest) SetFeature(v FeatureCreate) {
	o.Feature = v
}

func (o FeatureCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["feature"] = o.Feature

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeatureCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"feature",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeatureCreateRequest := _FeatureCreateRequest{}

	err = json.Unmarshal(data, &varFeatureCreateRequest)

	if err != nil {
		return err
	}

	*o = FeatureCreateRequest(varFeatureCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "feature")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeatureCreateRequest struct {
	value *FeatureCreateRequest
	isSet bool
}

func (v NullableFeatureCreateRequest) Get() *FeatureCreateRequest {
	return v.value
}

func (v *NullableFeatureCreateRequest) Set(val *FeatureCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureCreateRequest(val *FeatureCreateRequest) *NullableFeatureCreateRequest {
	return &NullableFeatureCreateRequest{value: val, isSet: true}
}

func (v NullableFeatureCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
