/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"fmt"
)

// checks if the StrategicModelCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategicModelCreate{}

// StrategicModelCreate struct for StrategicModelCreate
type StrategicModelCreate struct {
	// Strategic model name
	Name string `json:"name"`
	// Type of canvas (e.g., Opportunity, Lean Canvas)
	Kind string `json:"kind"`
	// Strategic model description
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StrategicModelCreate StrategicModelCreate

// NewStrategicModelCreate instantiates a new StrategicModelCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategicModelCreate(name string, kind string) *StrategicModelCreate {
	this := StrategicModelCreate{}
	this.Name = name
	this.Kind = kind
	return &this
}

// NewStrategicModelCreateWithDefaults instantiates a new StrategicModelCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategicModelCreateWithDefaults() *StrategicModelCreate {
	this := StrategicModelCreate{}
	return &this
}

// GetName returns the Name field value
func (o *StrategicModelCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StrategicModelCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StrategicModelCreate) SetName(v string) {
	o.Name = v
}

// GetKind returns the Kind field value
func (o *StrategicModelCreate) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *StrategicModelCreate) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *StrategicModelCreate) SetKind(v string) {
	o.Kind = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *StrategicModelCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *StrategicModelCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *StrategicModelCreate) SetDescription(v string) {
	o.Description = &v
}

func (o StrategicModelCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategicModelCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["kind"] = o.Kind
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrategicModelCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrategicModelCreate := _StrategicModelCreate{}

	err = json.Unmarshal(data, &varStrategicModelCreate)

	if err != nil {
		return err
	}

	*o = StrategicModelCreate(varStrategicModelCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrategicModelCreate struct {
	value *StrategicModelCreate
	isSet bool
}

func (v NullableStrategicModelCreate) Get() *StrategicModelCreate {
	return v.value
}

func (v *NullableStrategicModelCreate) Set(val *StrategicModelCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategicModelCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategicModelCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategicModelCreate(val *StrategicModelCreate) *NullableStrategicModelCreate {
	return &NullableStrategicModelCreate{value: val, isSet: true}
}

func (v NullableStrategicModelCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategicModelCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
