/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the WorkflowsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkflowsResponse{}

// WorkflowsResponse struct for WorkflowsResponse
type WorkflowsResponse struct {
	Workflows            []Workflow `json:"workflows,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WorkflowsResponse WorkflowsResponse

// NewWorkflowsResponse instantiates a new WorkflowsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowsResponse() *WorkflowsResponse {
	this := WorkflowsResponse{}
	return &this
}

// NewWorkflowsResponseWithDefaults instantiates a new WorkflowsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowsResponseWithDefaults() *WorkflowsResponse {
	this := WorkflowsResponse{}
	return &this
}

// GetWorkflows returns the Workflows field value if set, zero value otherwise.
func (o *WorkflowsResponse) GetWorkflows() []Workflow {
	if o == nil || IsNil(o.Workflows) {
		var ret []Workflow
		return ret
	}
	return o.Workflows
}

// GetWorkflowsOk returns a tuple with the Workflows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowsResponse) GetWorkflowsOk() ([]Workflow, bool) {
	if o == nil || IsNil(o.Workflows) {
		return nil, false
	}
	return o.Workflows, true
}

// HasWorkflows returns a boolean if a field has been set.
func (o *WorkflowsResponse) HasWorkflows() bool {
	if o != nil && !IsNil(o.Workflows) {
		return true
	}

	return false
}

// SetWorkflows gets a reference to the given []Workflow and assigns it to the Workflows field.
func (o *WorkflowsResponse) SetWorkflows(v []Workflow) {
	o.Workflows = v
}

func (o WorkflowsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkflowsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Workflows) {
		toSerialize["workflows"] = o.Workflows
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkflowsResponse) UnmarshalJSON(data []byte) (err error) {
	varWorkflowsResponse := _WorkflowsResponse{}

	err = json.Unmarshal(data, &varWorkflowsResponse)

	if err != nil {
		return err
	}

	*o = WorkflowsResponse(varWorkflowsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "workflows")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkflowsResponse struct {
	value *WorkflowsResponse
	isSet bool
}

func (v NullableWorkflowsResponse) Get() *WorkflowsResponse {
	return v.value
}

func (v *NullableWorkflowsResponse) Set(val *WorkflowsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowsResponse(val *WorkflowsResponse) *NullableWorkflowsResponse {
	return &NullableWorkflowsResponse{value: val, isSet: true}
}

func (v NullableWorkflowsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
