/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"time"
)

// checks if the IdeaOrganization type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdeaOrganization{}

// IdeaOrganization struct for IdeaOrganization
type IdeaOrganization struct {
	Id                   *string         `json:"id,omitempty"`
	Name                 *string         `json:"name,omitempty"`
	ReferenceNum         *string         `json:"reference_num,omitempty"`
	Url                  *string         `json:"url,omitempty"`
	CreatedAt            *time.Time      `json:"created_at,omitempty"`
	UpdatedAt            *time.Time      `json:"updated_at,omitempty"`
	EndorsementsCount    *int32          `json:"endorsements_count,omitempty"`
	EmailDomains         NullableString  `json:"email_domains,omitempty"`
	Revenue              NullableFloat64 `json:"revenue,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _IdeaOrganization IdeaOrganization

// NewIdeaOrganization instantiates a new IdeaOrganization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdeaOrganization() *IdeaOrganization {
	this := IdeaOrganization{}
	return &this
}

// NewIdeaOrganizationWithDefaults instantiates a new IdeaOrganization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdeaOrganizationWithDefaults() *IdeaOrganization {
	this := IdeaOrganization{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IdeaOrganization) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganization) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IdeaOrganization) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IdeaOrganization) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IdeaOrganization) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganization) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IdeaOrganization) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IdeaOrganization) SetName(v string) {
	o.Name = &v
}

// GetReferenceNum returns the ReferenceNum field value if set, zero value otherwise.
func (o *IdeaOrganization) GetReferenceNum() string {
	if o == nil || IsNil(o.ReferenceNum) {
		var ret string
		return ret
	}
	return *o.ReferenceNum
}

// GetReferenceNumOk returns a tuple with the ReferenceNum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganization) GetReferenceNumOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceNum) {
		return nil, false
	}
	return o.ReferenceNum, true
}

// HasReferenceNum returns a boolean if a field has been set.
func (o *IdeaOrganization) HasReferenceNum() bool {
	if o != nil && !IsNil(o.ReferenceNum) {
		return true
	}

	return false
}

// SetReferenceNum gets a reference to the given string and assigns it to the ReferenceNum field.
func (o *IdeaOrganization) SetReferenceNum(v string) {
	o.ReferenceNum = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *IdeaOrganization) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganization) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *IdeaOrganization) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *IdeaOrganization) SetUrl(v string) {
	o.Url = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *IdeaOrganization) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganization) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *IdeaOrganization) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *IdeaOrganization) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *IdeaOrganization) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganization) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *IdeaOrganization) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *IdeaOrganization) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetEndorsementsCount returns the EndorsementsCount field value if set, zero value otherwise.
func (o *IdeaOrganization) GetEndorsementsCount() int32 {
	if o == nil || IsNil(o.EndorsementsCount) {
		var ret int32
		return ret
	}
	return *o.EndorsementsCount
}

// GetEndorsementsCountOk returns a tuple with the EndorsementsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdeaOrganization) GetEndorsementsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.EndorsementsCount) {
		return nil, false
	}
	return o.EndorsementsCount, true
}

// HasEndorsementsCount returns a boolean if a field has been set.
func (o *IdeaOrganization) HasEndorsementsCount() bool {
	if o != nil && !IsNil(o.EndorsementsCount) {
		return true
	}

	return false
}

// SetEndorsementsCount gets a reference to the given int32 and assigns it to the EndorsementsCount field.
func (o *IdeaOrganization) SetEndorsementsCount(v int32) {
	o.EndorsementsCount = &v
}

// GetEmailDomains returns the EmailDomains field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdeaOrganization) GetEmailDomains() string {
	if o == nil || IsNil(o.EmailDomains.Get()) {
		var ret string
		return ret
	}
	return *o.EmailDomains.Get()
}

// GetEmailDomainsOk returns a tuple with the EmailDomains field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdeaOrganization) GetEmailDomainsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmailDomains.Get(), o.EmailDomains.IsSet()
}

// HasEmailDomains returns a boolean if a field has been set.
func (o *IdeaOrganization) HasEmailDomains() bool {
	if o != nil && o.EmailDomains.IsSet() {
		return true
	}

	return false
}

// SetEmailDomains gets a reference to the given NullableString and assigns it to the EmailDomains field.
func (o *IdeaOrganization) SetEmailDomains(v string) {
	o.EmailDomains.Set(&v)
}

// SetEmailDomainsNil sets the value for EmailDomains to be an explicit nil
func (o *IdeaOrganization) SetEmailDomainsNil() {
	o.EmailDomains.Set(nil)
}

// UnsetEmailDomains ensures that no value is present for EmailDomains, not even an explicit nil
func (o *IdeaOrganization) UnsetEmailDomains() {
	o.EmailDomains.Unset()
}

// GetRevenue returns the Revenue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IdeaOrganization) GetRevenue() float64 {
	if o == nil || IsNil(o.Revenue.Get()) {
		var ret float64
		return ret
	}
	return *o.Revenue.Get()
}

// GetRevenueOk returns a tuple with the Revenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IdeaOrganization) GetRevenueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Revenue.Get(), o.Revenue.IsSet()
}

// HasRevenue returns a boolean if a field has been set.
func (o *IdeaOrganization) HasRevenue() bool {
	if o != nil && o.Revenue.IsSet() {
		return true
	}

	return false
}

// SetRevenue gets a reference to the given NullableFloat64 and assigns it to the Revenue field.
func (o *IdeaOrganization) SetRevenue(v float64) {
	o.Revenue.Set(&v)
}

// SetRevenueNil sets the value for Revenue to be an explicit nil
func (o *IdeaOrganization) SetRevenueNil() {
	o.Revenue.Set(nil)
}

// UnsetRevenue ensures that no value is present for Revenue, not even an explicit nil
func (o *IdeaOrganization) UnsetRevenue() {
	o.Revenue.Unset()
}

func (o IdeaOrganization) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdeaOrganization) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ReferenceNum) {
		toSerialize["reference_num"] = o.ReferenceNum
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.EndorsementsCount) {
		toSerialize["endorsements_count"] = o.EndorsementsCount
	}
	if o.EmailDomains.IsSet() {
		toSerialize["email_domains"] = o.EmailDomains.Get()
	}
	if o.Revenue.IsSet() {
		toSerialize["revenue"] = o.Revenue.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *IdeaOrganization) UnmarshalJSON(data []byte) (err error) {
	varIdeaOrganization := _IdeaOrganization{}

	err = json.Unmarshal(data, &varIdeaOrganization)

	if err != nil {
		return err
	}

	*o = IdeaOrganization(varIdeaOrganization)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "reference_num")
		delete(additionalProperties, "url")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "endorsements_count")
		delete(additionalProperties, "email_domains")
		delete(additionalProperties, "revenue")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableIdeaOrganization struct {
	value *IdeaOrganization
	isSet bool
}

func (v NullableIdeaOrganization) Get() *IdeaOrganization {
	return v.value
}

func (v *NullableIdeaOrganization) Set(val *IdeaOrganization) {
	v.value = val
	v.isSet = true
}

func (v NullableIdeaOrganization) IsSet() bool {
	return v.isSet
}

func (v *NullableIdeaOrganization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdeaOrganization(val *IdeaOrganization) *NullableIdeaOrganization {
	return &NullableIdeaOrganization{value: val, isSet: true}
}

func (v NullableIdeaOrganization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdeaOrganization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
