/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the RequirementsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequirementsResponse{}

// RequirementsResponse struct for RequirementsResponse
type RequirementsResponse struct {
	Requirements         []RequirementMeta `json:"requirements,omitempty"`
	Pagination           *Pagination       `json:"pagination,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RequirementsResponse RequirementsResponse

// NewRequirementsResponse instantiates a new RequirementsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequirementsResponse() *RequirementsResponse {
	this := RequirementsResponse{}
	return &this
}

// NewRequirementsResponseWithDefaults instantiates a new RequirementsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequirementsResponseWithDefaults() *RequirementsResponse {
	this := RequirementsResponse{}
	return &this
}

// GetRequirements returns the Requirements field value if set, zero value otherwise.
func (o *RequirementsResponse) GetRequirements() []RequirementMeta {
	if o == nil || IsNil(o.Requirements) {
		var ret []RequirementMeta
		return ret
	}
	return o.Requirements
}

// GetRequirementsOk returns a tuple with the Requirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequirementsResponse) GetRequirementsOk() ([]RequirementMeta, bool) {
	if o == nil || IsNil(o.Requirements) {
		return nil, false
	}
	return o.Requirements, true
}

// HasRequirements returns a boolean if a field has been set.
func (o *RequirementsResponse) HasRequirements() bool {
	if o != nil && !IsNil(o.Requirements) {
		return true
	}

	return false
}

// SetRequirements gets a reference to the given []RequirementMeta and assigns it to the Requirements field.
func (o *RequirementsResponse) SetRequirements(v []RequirementMeta) {
	o.Requirements = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *RequirementsResponse) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequirementsResponse) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *RequirementsResponse) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *RequirementsResponse) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o RequirementsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequirementsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requirements) {
		toSerialize["requirements"] = o.Requirements
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RequirementsResponse) UnmarshalJSON(data []byte) (err error) {
	varRequirementsResponse := _RequirementsResponse{}

	err = json.Unmarshal(data, &varRequirementsResponse)

	if err != nil {
		return err
	}

	*o = RequirementsResponse(varRequirementsResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "requirements")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRequirementsResponse struct {
	value *RequirementsResponse
	isSet bool
}

func (v NullableRequirementsResponse) Get() *RequirementsResponse {
	return v.value
}

func (v *NullableRequirementsResponse) Set(val *RequirementsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRequirementsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRequirementsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequirementsResponse(val *RequirementsResponse) *NullableRequirementsResponse {
	return &NullableRequirementsResponse{value: val, isSet: true}
}

func (v NullableRequirementsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequirementsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
