/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the InitiativeUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InitiativeUpdate{}

// InitiativeUpdate struct for InitiativeUpdate
type InitiativeUpdate struct {
	Name                 *string        `json:"name,omitempty"`
	Description          *string        `json:"description,omitempty"`
	WorkflowStatus       *string        `json:"workflow_status,omitempty"`
	StartDate            NullableString `json:"start_date,omitempty"`
	EndDate              NullableString `json:"end_date,omitempty"`
	Value                *float64       `json:"value,omitempty"`
	Effort               *float64       `json:"effort,omitempty"`
	Color                *string        `json:"color,omitempty"`
	Presented            *bool          `json:"presented,omitempty"`
	ProgressSource       *string        `json:"progress_source,omitempty"`
	Progress             *float64       `json:"progress,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InitiativeUpdate InitiativeUpdate

// NewInitiativeUpdate instantiates a new InitiativeUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInitiativeUpdate() *InitiativeUpdate {
	this := InitiativeUpdate{}
	return &this
}

// NewInitiativeUpdateWithDefaults instantiates a new InitiativeUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInitiativeUpdateWithDefaults() *InitiativeUpdate {
	this := InitiativeUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InitiativeUpdate) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InitiativeUpdate) SetDescription(v string) {
	o.Description = &v
}

// GetWorkflowStatus returns the WorkflowStatus field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetWorkflowStatus() string {
	if o == nil || IsNil(o.WorkflowStatus) {
		var ret string
		return ret
	}
	return *o.WorkflowStatus
}

// GetWorkflowStatusOk returns a tuple with the WorkflowStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetWorkflowStatusOk() (*string, bool) {
	if o == nil || IsNil(o.WorkflowStatus) {
		return nil, false
	}
	return o.WorkflowStatus, true
}

// HasWorkflowStatus returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasWorkflowStatus() bool {
	if o != nil && !IsNil(o.WorkflowStatus) {
		return true
	}

	return false
}

// SetWorkflowStatus gets a reference to the given string and assigns it to the WorkflowStatus field.
func (o *InitiativeUpdate) SetWorkflowStatus(v string) {
	o.WorkflowStatus = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InitiativeUpdate) GetStartDate() string {
	if o == nil || IsNil(o.StartDate.Get()) {
		var ret string
		return ret
	}
	return *o.StartDate.Get()
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InitiativeUpdate) GetStartDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StartDate.Get(), o.StartDate.IsSet()
}

// HasStartDate returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasStartDate() bool {
	if o != nil && o.StartDate.IsSet() {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given NullableString and assigns it to the StartDate field.
func (o *InitiativeUpdate) SetStartDate(v string) {
	o.StartDate.Set(&v)
}

// SetStartDateNil sets the value for StartDate to be an explicit nil
func (o *InitiativeUpdate) SetStartDateNil() {
	o.StartDate.Set(nil)
}

// UnsetStartDate ensures that no value is present for StartDate, not even an explicit nil
func (o *InitiativeUpdate) UnsetStartDate() {
	o.StartDate.Unset()
}

// GetEndDate returns the EndDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InitiativeUpdate) GetEndDate() string {
	if o == nil || IsNil(o.EndDate.Get()) {
		var ret string
		return ret
	}
	return *o.EndDate.Get()
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InitiativeUpdate) GetEndDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndDate.Get(), o.EndDate.IsSet()
}

// HasEndDate returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasEndDate() bool {
	if o != nil && o.EndDate.IsSet() {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given NullableString and assigns it to the EndDate field.
func (o *InitiativeUpdate) SetEndDate(v string) {
	o.EndDate.Set(&v)
}

// SetEndDateNil sets the value for EndDate to be an explicit nil
func (o *InitiativeUpdate) SetEndDateNil() {
	o.EndDate.Set(nil)
}

// UnsetEndDate ensures that no value is present for EndDate, not even an explicit nil
func (o *InitiativeUpdate) UnsetEndDate() {
	o.EndDate.Unset()
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetValue() float64 {
	if o == nil || IsNil(o.Value) {
		var ret float64
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetValueOk() (*float64, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given float64 and assigns it to the Value field.
func (o *InitiativeUpdate) SetValue(v float64) {
	o.Value = &v
}

// GetEffort returns the Effort field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetEffort() float64 {
	if o == nil || IsNil(o.Effort) {
		var ret float64
		return ret
	}
	return *o.Effort
}

// GetEffortOk returns a tuple with the Effort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetEffortOk() (*float64, bool) {
	if o == nil || IsNil(o.Effort) {
		return nil, false
	}
	return o.Effort, true
}

// HasEffort returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasEffort() bool {
	if o != nil && !IsNil(o.Effort) {
		return true
	}

	return false
}

// SetEffort gets a reference to the given float64 and assigns it to the Effort field.
func (o *InitiativeUpdate) SetEffort(v float64) {
	o.Effort = &v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetColor() string {
	if o == nil || IsNil(o.Color) {
		var ret string
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetColorOk() (*string, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given string and assigns it to the Color field.
func (o *InitiativeUpdate) SetColor(v string) {
	o.Color = &v
}

// GetPresented returns the Presented field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetPresented() bool {
	if o == nil || IsNil(o.Presented) {
		var ret bool
		return ret
	}
	return *o.Presented
}

// GetPresentedOk returns a tuple with the Presented field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetPresentedOk() (*bool, bool) {
	if o == nil || IsNil(o.Presented) {
		return nil, false
	}
	return o.Presented, true
}

// HasPresented returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasPresented() bool {
	if o != nil && !IsNil(o.Presented) {
		return true
	}

	return false
}

// SetPresented gets a reference to the given bool and assigns it to the Presented field.
func (o *InitiativeUpdate) SetPresented(v bool) {
	o.Presented = &v
}

// GetProgressSource returns the ProgressSource field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetProgressSource() string {
	if o == nil || IsNil(o.ProgressSource) {
		var ret string
		return ret
	}
	return *o.ProgressSource
}

// GetProgressSourceOk returns a tuple with the ProgressSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetProgressSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ProgressSource) {
		return nil, false
	}
	return o.ProgressSource, true
}

// HasProgressSource returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasProgressSource() bool {
	if o != nil && !IsNil(o.ProgressSource) {
		return true
	}

	return false
}

// SetProgressSource gets a reference to the given string and assigns it to the ProgressSource field.
func (o *InitiativeUpdate) SetProgressSource(v string) {
	o.ProgressSource = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *InitiativeUpdate) GetProgress() float64 {
	if o == nil || IsNil(o.Progress) {
		var ret float64
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InitiativeUpdate) GetProgressOk() (*float64, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *InitiativeUpdate) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given float64 and assigns it to the Progress field.
func (o *InitiativeUpdate) SetProgress(v float64) {
	o.Progress = &v
}

func (o InitiativeUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InitiativeUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.WorkflowStatus) {
		toSerialize["workflow_status"] = o.WorkflowStatus
	}
	if o.StartDate.IsSet() {
		toSerialize["start_date"] = o.StartDate.Get()
	}
	if o.EndDate.IsSet() {
		toSerialize["end_date"] = o.EndDate.Get()
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Effort) {
		toSerialize["effort"] = o.Effort
	}
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Presented) {
		toSerialize["presented"] = o.Presented
	}
	if !IsNil(o.ProgressSource) {
		toSerialize["progress_source"] = o.ProgressSource
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InitiativeUpdate) UnmarshalJSON(data []byte) (err error) {
	varInitiativeUpdate := _InitiativeUpdate{}

	err = json.Unmarshal(data, &varInitiativeUpdate)

	if err != nil {
		return err
	}

	*o = InitiativeUpdate(varInitiativeUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "workflow_status")
		delete(additionalProperties, "start_date")
		delete(additionalProperties, "end_date")
		delete(additionalProperties, "value")
		delete(additionalProperties, "effort")
		delete(additionalProperties, "color")
		delete(additionalProperties, "presented")
		delete(additionalProperties, "progress_source")
		delete(additionalProperties, "progress")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInitiativeUpdate struct {
	value *InitiativeUpdate
	isSet bool
}

func (v NullableInitiativeUpdate) Get() *InitiativeUpdate {
	return v.value
}

func (v *NullableInitiativeUpdate) Set(val *InitiativeUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableInitiativeUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableInitiativeUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInitiativeUpdate(val *InitiativeUpdate) *NullableInitiativeUpdate {
	return &NullableInitiativeUpdate{value: val, isSet: true}
}

func (v NullableInitiativeUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInitiativeUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
