/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"fmt"
)

// checks if the ProductCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductCreate{}

// ProductCreate struct for ProductCreate
type ProductCreate struct {
	// Name of the product
	Name string `json:"name"`
	// Abbreviation used as prefix on all features
	ReferencePrefix string `json:"reference_prefix"`
	// Description of the product (HTML allowed)
	Description *string `json:"description,omitempty"`
	// Numeric ID or prefix of parent product line
	ParentId *string `json:"parent_id,omitempty"`
	// Type of workspace (product_workspace, it_workspace, marketing_workspace, etc.)
	WorkspaceType *string `json:"workspace_type,omitempty"`
	// Set to true to create a product line
	ProductLine *bool `json:"product_line,omitempty"`
	// Required if creating a product line
	ProductLineType      *string `json:"product_line_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProductCreate ProductCreate

// NewProductCreate instantiates a new ProductCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductCreate(name string, referencePrefix string) *ProductCreate {
	this := ProductCreate{}
	this.Name = name
	this.ReferencePrefix = referencePrefix
	return &this
}

// NewProductCreateWithDefaults instantiates a new ProductCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductCreateWithDefaults() *ProductCreate {
	this := ProductCreate{}
	return &this
}

// GetName returns the Name field value
func (o *ProductCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProductCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProductCreate) SetName(v string) {
	o.Name = v
}

// GetReferencePrefix returns the ReferencePrefix field value
func (o *ProductCreate) GetReferencePrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferencePrefix
}

// GetReferencePrefixOk returns a tuple with the ReferencePrefix field value
// and a boolean to check if the value has been set.
func (o *ProductCreate) GetReferencePrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferencePrefix, true
}

// SetReferencePrefix sets field value
func (o *ProductCreate) SetReferencePrefix(v string) {
	o.ReferencePrefix = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ProductCreate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductCreate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ProductCreate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ProductCreate) SetDescription(v string) {
	o.Description = &v
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *ProductCreate) GetParentId() string {
	if o == nil || IsNil(o.ParentId) {
		var ret string
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductCreate) GetParentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *ProductCreate) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given string and assigns it to the ParentId field.
func (o *ProductCreate) SetParentId(v string) {
	o.ParentId = &v
}

// GetWorkspaceType returns the WorkspaceType field value if set, zero value otherwise.
func (o *ProductCreate) GetWorkspaceType() string {
	if o == nil || IsNil(o.WorkspaceType) {
		var ret string
		return ret
	}
	return *o.WorkspaceType
}

// GetWorkspaceTypeOk returns a tuple with the WorkspaceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductCreate) GetWorkspaceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.WorkspaceType) {
		return nil, false
	}
	return o.WorkspaceType, true
}

// HasWorkspaceType returns a boolean if a field has been set.
func (o *ProductCreate) HasWorkspaceType() bool {
	if o != nil && !IsNil(o.WorkspaceType) {
		return true
	}

	return false
}

// SetWorkspaceType gets a reference to the given string and assigns it to the WorkspaceType field.
func (o *ProductCreate) SetWorkspaceType(v string) {
	o.WorkspaceType = &v
}

// GetProductLine returns the ProductLine field value if set, zero value otherwise.
func (o *ProductCreate) GetProductLine() bool {
	if o == nil || IsNil(o.ProductLine) {
		var ret bool
		return ret
	}
	return *o.ProductLine
}

// GetProductLineOk returns a tuple with the ProductLine field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductCreate) GetProductLineOk() (*bool, bool) {
	if o == nil || IsNil(o.ProductLine) {
		return nil, false
	}
	return o.ProductLine, true
}

// HasProductLine returns a boolean if a field has been set.
func (o *ProductCreate) HasProductLine() bool {
	if o != nil && !IsNil(o.ProductLine) {
		return true
	}

	return false
}

// SetProductLine gets a reference to the given bool and assigns it to the ProductLine field.
func (o *ProductCreate) SetProductLine(v bool) {
	o.ProductLine = &v
}

// GetProductLineType returns the ProductLineType field value if set, zero value otherwise.
func (o *ProductCreate) GetProductLineType() string {
	if o == nil || IsNil(o.ProductLineType) {
		var ret string
		return ret
	}
	return *o.ProductLineType
}

// GetProductLineTypeOk returns a tuple with the ProductLineType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductCreate) GetProductLineTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ProductLineType) {
		return nil, false
	}
	return o.ProductLineType, true
}

// HasProductLineType returns a boolean if a field has been set.
func (o *ProductCreate) HasProductLineType() bool {
	if o != nil && !IsNil(o.ProductLineType) {
		return true
	}

	return false
}

// SetProductLineType gets a reference to the given string and assigns it to the ProductLineType field.
func (o *ProductCreate) SetProductLineType(v string) {
	o.ProductLineType = &v
}

func (o ProductCreate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["reference_prefix"] = o.ReferencePrefix
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}
	if !IsNil(o.WorkspaceType) {
		toSerialize["workspace_type"] = o.WorkspaceType
	}
	if !IsNil(o.ProductLine) {
		toSerialize["product_line"] = o.ProductLine
	}
	if !IsNil(o.ProductLineType) {
		toSerialize["product_line_type"] = o.ProductLineType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProductCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"reference_prefix",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductCreate := _ProductCreate{}

	err = json.Unmarshal(data, &varProductCreate)

	if err != nil {
		return err
	}

	*o = ProductCreate(varProductCreate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "reference_prefix")
		delete(additionalProperties, "description")
		delete(additionalProperties, "parent_id")
		delete(additionalProperties, "workspace_type")
		delete(additionalProperties, "product_line")
		delete(additionalProperties, "product_line_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProductCreate struct {
	value *ProductCreate
	isSet bool
}

func (v NullableProductCreate) Get() *ProductCreate {
	return v.value
}

func (v *NullableProductCreate) Set(val *ProductCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableProductCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableProductCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductCreate(val *ProductCreate) *NullableProductCreate {
	return &NullableProductCreate{value: val, isSet: true}
}

func (v NullableProductCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
