/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the StrategicModelComponent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategicModelComponent{}

// StrategicModelComponent A component (block) within a strategic model
type StrategicModelComponent struct {
	Id *string `json:"id,omitempty"`
	// Block name (e.g., Users & Customers, Problems, Solutions)
	Name *string `json:"name,omitempty"`
	// Content of the block (HTML allowed)
	Description *string `json:"description,omitempty"`
	// Display order position
	Position             *int64 `json:"position,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StrategicModelComponent StrategicModelComponent

// NewStrategicModelComponent instantiates a new StrategicModelComponent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategicModelComponent() *StrategicModelComponent {
	this := StrategicModelComponent{}
	return &this
}

// NewStrategicModelComponentWithDefaults instantiates a new StrategicModelComponent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategicModelComponentWithDefaults() *StrategicModelComponent {
	this := StrategicModelComponent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StrategicModelComponent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelComponent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StrategicModelComponent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StrategicModelComponent) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StrategicModelComponent) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelComponent) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StrategicModelComponent) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StrategicModelComponent) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *StrategicModelComponent) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelComponent) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *StrategicModelComponent) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *StrategicModelComponent) SetDescription(v string) {
	o.Description = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *StrategicModelComponent) GetPosition() int64 {
	if o == nil || IsNil(o.Position) {
		var ret int64
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelComponent) GetPositionOk() (*int64, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *StrategicModelComponent) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given int64 and assigns it to the Position field.
func (o *StrategicModelComponent) SetPosition(v int64) {
	o.Position = &v
}

func (o StrategicModelComponent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategicModelComponent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrategicModelComponent) UnmarshalJSON(data []byte) (err error) {
	varStrategicModelComponent := _StrategicModelComponent{}

	err = json.Unmarshal(data, &varStrategicModelComponent)

	if err != nil {
		return err
	}

	*o = StrategicModelComponent(varStrategicModelComponent)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "position")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrategicModelComponent struct {
	value *StrategicModelComponent
	isSet bool
}

func (v NullableStrategicModelComponent) Get() *StrategicModelComponent {
	return v.value
}

func (v *NullableStrategicModelComponent) Set(val *StrategicModelComponent) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategicModelComponent) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategicModelComponent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategicModelComponent(val *StrategicModelComponent) *NullableStrategicModelComponent {
	return &NullableStrategicModelComponent{value: val, isSet: true}
}

func (v NullableStrategicModelComponent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategicModelComponent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
