/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
)

// checks if the StrategicModelUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategicModelUpdate{}

// StrategicModelUpdate struct for StrategicModelUpdate
type StrategicModelUpdate struct {
	Name                 *string `json:"name,omitempty"`
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _StrategicModelUpdate StrategicModelUpdate

// NewStrategicModelUpdate instantiates a new StrategicModelUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategicModelUpdate() *StrategicModelUpdate {
	this := StrategicModelUpdate{}
	return &this
}

// NewStrategicModelUpdateWithDefaults instantiates a new StrategicModelUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategicModelUpdateWithDefaults() *StrategicModelUpdate {
	this := StrategicModelUpdate{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *StrategicModelUpdate) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelUpdate) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *StrategicModelUpdate) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *StrategicModelUpdate) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *StrategicModelUpdate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategicModelUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *StrategicModelUpdate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *StrategicModelUpdate) SetDescription(v string) {
	o.Description = &v
}

func (o StrategicModelUpdate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategicModelUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrategicModelUpdate) UnmarshalJSON(data []byte) (err error) {
	varStrategicModelUpdate := _StrategicModelUpdate{}

	err = json.Unmarshal(data, &varStrategicModelUpdate)

	if err != nil {
		return err
	}

	*o = StrategicModelUpdate(varStrategicModelUpdate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrategicModelUpdate struct {
	value *StrategicModelUpdate
	isSet bool
}

func (v NullableStrategicModelUpdate) Get() *StrategicModelUpdate {
	return v.value
}

func (v *NullableStrategicModelUpdate) Set(val *StrategicModelUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategicModelUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategicModelUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategicModelUpdate(val *StrategicModelUpdate) *NullableStrategicModelUpdate {
	return &NullableStrategicModelUpdate{value: val, isSet: true}
}

func (v NullableStrategicModelUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategicModelUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
