/*
Aha.io API

Go client for the Aha.io product management API.  This OpenAPI specification is used to generate the internal API client via ogen. The public SDK provides ergonomic wrappers on top of the generated client.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aha

import (
	"encoding/json"
	"fmt"
)

// checks if the ReleaseUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReleaseUpdateRequest{}

// ReleaseUpdateRequest struct for ReleaseUpdateRequest
type ReleaseUpdateRequest struct {
	Release              ReleaseUpdate `json:"release"`
	AdditionalProperties map[string]interface{}
}

type _ReleaseUpdateRequest ReleaseUpdateRequest

// NewReleaseUpdateRequest instantiates a new ReleaseUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReleaseUpdateRequest(release ReleaseUpdate) *ReleaseUpdateRequest {
	this := ReleaseUpdateRequest{}
	this.Release = release
	return &this
}

// NewReleaseUpdateRequestWithDefaults instantiates a new ReleaseUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReleaseUpdateRequestWithDefaults() *ReleaseUpdateRequest {
	this := ReleaseUpdateRequest{}
	return &this
}

// GetRelease returns the Release field value
func (o *ReleaseUpdateRequest) GetRelease() ReleaseUpdate {
	if o == nil {
		var ret ReleaseUpdate
		return ret
	}

	return o.Release
}

// GetReleaseOk returns a tuple with the Release field value
// and a boolean to check if the value has been set.
func (o *ReleaseUpdateRequest) GetReleaseOk() (*ReleaseUpdate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Release, true
}

// SetRelease sets field value
func (o *ReleaseUpdateRequest) SetRelease(v ReleaseUpdate) {
	o.Release = v
}

func (o ReleaseUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReleaseUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["release"] = o.Release

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReleaseUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"release",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReleaseUpdateRequest := _ReleaseUpdateRequest{}

	err = json.Unmarshal(data, &varReleaseUpdateRequest)

	if err != nil {
		return err
	}

	*o = ReleaseUpdateRequest(varReleaseUpdateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "release")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReleaseUpdateRequest struct {
	value *ReleaseUpdateRequest
	isSet bool
}

func (v NullableReleaseUpdateRequest) Get() *ReleaseUpdateRequest {
	return v.value
}

func (v *NullableReleaseUpdateRequest) Set(val *ReleaseUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReleaseUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReleaseUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReleaseUpdateRequest(val *ReleaseUpdateRequest) *NullableReleaseUpdateRequest {
	return &NullableReleaseUpdateRequest{value: val, isSet: true}
}

func (v NullableReleaseUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReleaseUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
